server:
  port: 8081
#  servlet:
#    context-path: /api
spring:
  webflux:
    base-path: /api
  application:
    name: ai-code-helper
zhipu:
  ai:
    api-key: 3c9be82654a04f959c2c11ec26f0ca65.iMEWa9tsYuGgCMsZ
    model: glm-4-flash
baidu:
  map:
    api-key: ""
